version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ENV=development
    volumes:
      - ./frontend:/src
      - /src/node_modules
    command: npm run dev
    
